### Update A Record
# response should be 200
https://unifi-cloudflare-ddns.{{workerDomain}}.workers.dev/update
    ?ip={{ip}}
    &hostname={{hostname}}
Authorization: Basic {{username}} {{password}}


### No Auth Test
# will fail with bad request error
https://unifi-cloudflare-ddns.{{workerDomain}}.workers.dev/update
    ?ip={{ip}}
    &hostname={{hostname}}